### ISSUE TITLE
VBUS Spezifikation

### ISSUE THREAD

**Issue by jampy** [danielwippermann/resol-vbus-logger.rs#1]
Hallo!

Sorry, kein wirkliches Problem, aber wo ist bitte die VBUS Spezifikation zu finden? 

Besten Dank und alles Gute im neuen Jahr!

**Comment by danielwippermann** [comment]
Hi und ebenfalls alles Gute und Gesundheit im neuen Jahr!

Die aktuelle VBus-Protokollspezifikation liegt unter:

http://danielwippermann.github.io/resol-vbus/#/md/docs/vbus-specification

Die Beschreibungen zum regler-spezifischen Payload gibt es dann separat unter:

http://danielwippermann.github.io/resol-vbus/#/vsf

Bis dann,
Daniel
