### ISSUE TITLE
Interessantes Projekt

### ISSUE THREAD

**Issue by ChR-iSz** [danielwippermann/resol-vbus-logger.rs#3]
Ein tolles Projekt. Vielen dank dafür, das die Arbeit und Dein Wissen über Github weitergegeben wird!!

Eine Kurze Nachfrage. Benötige ich den Resol Schnittstellenadapter MX/MX2 oder kann der Raspberry direkt am BUS angeschlossen werden?

**Comment by isarrider** [comment]
über eine kleine Schaltung kannst du ihn direkt an den Bus hängen,
hier ist zB eine (aber es geht sogar mit noch weniger Bauelementen):
https://github.com/arendst/Tasmota/discussions/10988

**Comment by ChR-iSz** [comment]
Danke für die Info.
Mittlerweile habe ich mir den Resol USB Schnittstellen Adapter für 80€ besorgt, und lese die Daten direkt über den USB Serial Port mit Debian aus. Zwar die teurere Variante, aber läuft sehr zuverlässig.
